"""fix_bike_inventory_unique_constraint

Revision ID: 3df0810a332f
Revises: e2d48d22dad8
Create Date: 2026-05-24 09:34:45.249634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df0810a332f'
down_revision: Union[str, Sequence[str], None] = 'e2d48d22dad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bike_inventory_bike_id_key'), 'bike_inventory', type_='unique')
    op.drop_index(op.f('ix_bike_inventory_bike_id'), table_name='bike_inventory')
    op.create_index(op.f('ix_bike_inventory_bike_id'), 'bike_inventory', ['bike_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bike_inventory_bike_id'), table_name='bike_inventory')
    op.create_index(op.f('ix_bike_inventory_bike_id'), 'bike_inventory', ['bike_id'], unique=False)
    op.create_unique_constraint(op.f('bike_inventory_bike_id_key'), 'bike_inventory', ['bike_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
