"""add rentalos subscription status to shop

Revision ID: 5f8894421a35
Revises: 15b8f2c4d6a1
Create Date: 2026-07-04 17:04:21.239653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f8894421a35'
down_revision: Union[str, Sequence[str], None] = '15b8f2c4d6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('rentalos_subscription_status', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('rentalos_subscription_end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'rentalos_subscription_end_date')
    op.drop_column('shops', 'rentalos_subscription_status')
    # ### end Alembic commands ###
