"""Added confirmed_at and completed_at columns in the booking table

Revision ID: 8e315f30fed3
Revises: e8ac63c34c59
Create Date: 2025-10-30 22:33:32.235381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e315f30fed3'
down_revision: Union[str, Sequence[str], None] = 'e8ac63c34c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
