"""added shop_id with shop.id as a FK

Revision ID: 90d061153e4a
Revises: 2c62cd571021
Create Date: 2025-10-27 22:54:01.832144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d061153e4a'
down_revision: Union[str, Sequence[str], None] = '2c62cd571021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike_inventory', sa.Column('shop_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_bike_inventory_shop_id'), 'bike_inventory', ['shop_id'], unique=False)
    op.create_foreign_key(None, 'bike_inventory', 'shops', ['shop_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bike_inventory', type_='foreignkey')
    op.drop_index(op.f('ix_bike_inventory_shop_id'), table_name='bike_inventory')
    op.drop_column('bike_inventory', 'shop_id')
    # ### end Alembic commands ###
