"""added magic link column

Revision ID: 9bdafe661149
Revises: 0003_backfill_bike_inventory
Create Date: 2026-05-21 17:28:06.491943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bdafe661149'
down_revision: Union[str, Sequence[str], None] = '0003_backfill_bike_inventory'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('magic_token', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by eAlembic - please adjust! ###
    op.drop_column('bookings', 'magic_token')
    # ### end Alembic commands ###
