"""Add UTR and UPI columns

Revision ID: e2d48d22dad8
Revises: 9bdafe661149
Create Date: 2026-05-22 23:44:57.388615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d48d22dad8'
down_revision: Union[str, Sequence[str], None] = '9bdafe661149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('upi_id', sa.String(length=50), nullable=True))
    op.add_column('bookings', sa.Column('utr_number', sa.String(length=12), nullable=True))
    op.add_column('bookings', sa.Column('token_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'token_amount')
    op.drop_column('bookings', 'utr_number')
    op.drop_column('shops', 'upi_id')
    # ### end Alembic commands ###
