"""added AdminUser model,schema and authentication to get all users

Revision ID: e8ac63c34c59
Revises: 90d061153e4a
Create Date: 2025-10-27 23:25:15.343983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ac63c34c59'
down_revision: Union[str, Sequence[str], None] = '90d061153e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
